### ISSUE TITLE
Violates CSP in Atom

### ISSUE THREAD

**Issue by lgeiger** [UziTech/atom-jasmine2-test-runner#14]
Hi @UziTech,

We recently switched to `atom-jasmine2-test-runner` in [Hydrogen](https://github.com/nteract/hydrogen) and it was working great. Since today our tests started failing for no reason: https://github.com/nteract/hydrogen/issues/747.

All our tests throw `EvalError: Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed source of script in the following Content Security Policy directive: "script-src 'self'".`.

This doesn't happen with the default Atom test runner.
Do you have an idea what could cause this issue? Maybe a updated dependency broke `atom-jasmine2-test-runner`?

**Comment by UziTech** [comment]
I can reproduce this in Atom 1.16

it seems to be an issue with  jasmine 2.6.0

**Comment by UziTech** [comment]
I released [v0.6.2](https://github.com/UziTech/atom-jasmine2-test-runner/releases/tag/v0.6.2) which should fix this for now by setting the jasmine dependency to "2.5.3"

**Comment by lgeiger** [comment]
Awesome thank you for the fast fix!

You might want to look into [`loophole`](https://github.com/atom/loophole) for working around Atoms CSP.

**Comment by UziTech** [comment]
Thanks I'll look into it.

I'll leave this issue open until we get a real fix.

**Comment by UziTech** [comment]
looks like loophole won't work because it doesn't allow the eval'd source to access local variables which jasmine needs. So the only way to fix this would be to get rid of the call to eval in jasmine.

I have created a pull request for this and will update the dependency once jasmine merges and releases it.

jasmine/jasmine#1330

**Comment by UziTech** [comment]
I just released [v0.7.0](https://github.com/UziTech/atom-jasmine2-test-runner/releases/tag/v0.7.0) which should work with Jasmine 2.6
