### ISSUE TITLE
Make pathwatcher a optional dependency

### ISSUE THREAD

**Issue by lgeiger** [UziTech/atom-jasmine2-test-runner#17]
Thanks for maintaining this module!

`v0.7.1` added `pathwatcher` as a dependency. Since it is a native module it can cause quite some pain during install for developers who don't have  properly set up their compilers (mainly Windows)  or use Atom beta.

It would be cool to make it a optional dependency.
What do you think?

**Comment by UziTech** [comment]
Good call. I set all of the spec-helper dependencies as optional in v0.7.2.

If you do need pathwatcher to work on windows try deleting the `node_modules` folder and running `apm i` instead of `npm i`

**Comment by UziTech** [comment]
@lgeiger I took this a step further and started lazy installing the spec-helper dependencies in `v0.8.0` so `pathwatcher` won't be installed at all unless it is set as a spec-helper.

Let me know if this has any issues. In testing it had a few issues on osx but I think those were just with the testing environment.
